// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :exec
INSERT INTO POSTS (ID, CREATED_AT, UPDATED_AT, TITLE, URL, DESCRIPTION, PUBLISHED_AT, FEED_ID)
VALUES ($1, $2,$3,$4,$5,$6, $7, $8)
`

type CreatePostParams struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt time.Time
	FeedID      uuid.UUID
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.ExecContext(ctx, createPost,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	return err
}

const getPostByUrl = `-- name: GetPostByUrl :one
SELECT
    ID,
    URL
FROM POSTS WHERE URL = $1 LIMIT 1
`

type GetPostByUrlRow struct {
	ID  uuid.UUID
	Url string
}

func (q *Queries) GetPostByUrl(ctx context.Context, url string) (GetPostByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getPostByUrl, url)
	var i GetPostByUrlRow
	err := row.Scan(&i.ID, &i.Url)
	return i, err
}

const getPostsByUserId = `-- name: GetPostsByUserId :many
select 
    posts.ID,
    posts.created_at,
    posts.updated_at,
    posts.title,
    posts.url,
    posts.description,
    posts.published_at,
    posts.feed_id
from posts 
inner join feed_follows on feed_follows.feed_id = posts.feed_id
where feed_follows.user_id = $1 
order by posts.published_at desc 
limit $2
`

type GetPostsByUserIdParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetPostsByUserId(ctx context.Context, arg GetPostsByUserIdParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByUserId, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
