-- name: CreateFeed :one
INSERT INTO FEEDS (ID, CREATED_AT, UPDATED_AT, NAME, URL, USER_ID)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING *;

-- name: GetAllFeeds :many
SELECT FEEDS.ID, FEEDS.NAME, FEEDS.URL, USERS.NAME AS USER_NAME FROM FEEDS INNER JOIN USERS ON USERS.ID = FEEDS.USER_ID;

-- name: CreateFeedFollow :one
WITH INSERTED_FEED_FOLLOW AS (
    INSERT INTO FEED_FOLLOWS (ID, CREATED_AT, UPDATED_AT, USER_ID, FEED_ID) 
    VALUES($1, $2, $3, $4, $5)
    RETURNING *
)

SELECT 
    INSERTED_FEED_FOLLOW.*,
    FEEDS.NAME AS FEED_NAME,
    USERS.NAME AS USER_NAME
FROM INSERTED_FEED_FOLLOW
INNER JOIN USERS ON USERS.ID = INSERTED_FEED_FOLLOW.USER_ID
INNER JOIN FEEDS ON FEEDS.ID = INSERTED_FEED_FOLLOW.FEED_ID;



-- name: GetFeedByUrl :one
SELECT FEEDS.ID, FEEDS.NAME, FEEDS.URL FROM FEEDS WHERE FEEDS.URL = $1;


-- name: GetFeedFollowsForUser :many
SELECT 
    FEED_FOLLOWS.USER_ID, 
    USERS.NAME AS USER_NAME,
    FEED_FOLLOWS.FEED_ID,
    FEEDS.NAME AS FEED_NAME
FROM FEED_FOLLOWS 
INNER JOIN USERS ON USERS.ID = FEED_FOLLOWS.USER_ID
INNER JOIN FEEDS ON FEEDS.ID = FEED_FOLLOWS.FEED_ID
WHERE USERS.ID = $1;


-- name: UnfollowFeedByUserIdAndFeedId :exec
DELETE FROM FEED_FOLLOWS 
WHERE feed_follows.user_id=$1 and feed_follows.feed_id =$2;

-- name: MarkFeedFetched :exec
UPDATE FEEDS SET UPDATED_AT = $1, LAST_FETCHED_AT = $2 WHERE ID = $3;

-- name: GetNextFeedToFetch :one
SELECT * FROM FEEDS ORDER BY LAST_FETCHED_AT ASC NULLS FIRST limit 1;
