-- +goose up
CREATE TABLE FEEDS (
	ID UUID PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	URL VARCHAR(200) NOT NULL,
	USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
	UNIQUE(URL)
);


-- +goose down
DROP TABLE FEEDS;

