-- +goose up
CREATE TABLE POSTS (
	ID UUID PRIMARY KEY,
	CREATED_AT TIMESTAMP NOT NULL,
	UPDATED_AT TIMESTAMP NOT NULL,
	TITLE VARCHAR(100) NOT NULL,
	URL VARCHAR(200) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	PUBLISHED_AT TIMESTAMP NOT NULL,
	FEED_ID UUID NOT NULL REFERENCES FEEDS(ID) ON DELETE CASCADE,
	UNIQUE(URL)
);

-- +goose down
DROP TABLE POSTS;
